module ItemsResponses
  def list_all_items
    [{:id=>17,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Empleado_Extra",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>1200, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>5,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"enterprise",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>149000, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>2,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"entrepreneur",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>0, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>18,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Nominapp Plan Base Aliados",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>299900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :inventory=>{:unit=>"unit"},
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>19,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Nominapp Plan Por Persona Aliados",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>7900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :inventory=>{:unit=>"unit"},
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>13,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Nominapp_Plan_Emprendedor",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>29900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>16,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Nominapp_Plan_Enterprise",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>169900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>15,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Nominapp_Plan_Pro",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>99900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>14,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Nominapp_Plan_Pyme",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>49900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>20,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Plan upgrade por persona",
      :description=>"Upgrade de plan por persona al mes",
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>80000, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"product",
      :item_type=>nil},
     {:id=>12,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Plan_Corporative_Nominapp",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>999900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>6,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Plan_Emprendedor_Nominapp",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>29900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>9,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Plan_Enterprise_Nominapp",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>149900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>11,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Plan_Gold_Nominapp",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>449900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>1,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Plan_Mensual_Nominapp",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>19900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>8,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Plan_Pro_Nominapp",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>99900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>7,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Plan_Pyme_Nominapp",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>49900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>10,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"Plan_Silver_Nominapp",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>249900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>4,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"pro",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>99000, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil},
     {:id=>3,
      :category=>{:id=>"5067", :name=>"Ventas"},
      :has_no_iva_days=>false,
      :name=>"pyme",
      :description=>nil,
      :reference=>nil,
      :status=>"active",
      :calculation_scale=>2,
      :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>49900, :currency=>{:code=>"COP", :symbol=>"$"}}],
      :tax=>[],
      :custom_fields=>[],
      :product_key=>nil,
      :type=>"simple",
      :item_type=>nil}]
  end

  def list_specific_item
    {:id=>1,
     :category=>{:id=>"5067", :name=>"Ventas"},
     :has_no_iva_days=>false,
     :name=>"Plan_Mensual_Nominapp",
     :description=>nil,
     :reference=>nil,
     :status=>"active",
     :calculation_scale=>2,
     :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>19900, :currency=>{:code=>"COP", :symbol=>"$"}}],
     :tax=>[],
     :custom_fields=>[],
     :product_key=>nil,
     :type=>"simple",
     :item_type=>nil}
  end

  def update_item_response
    {:id=>3,
     :category=>{:id=>"5067", :name=>"Ventas"},
     :has_no_iva_days=>false,
     :editable=>true,
     :deletable=>false,
     :name=>"new name leather",
     :description=>"Brown leather wallet with more details",
     :reference=>nil,
     :status=>"active",
     :calculation_scale=>2,
     :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>49900, :currency=>{:code=>"COP", :symbol=>"$"}}],
     :tax=>[],
     :custom_fields=>[],
     :product_key=>nil,
     :type=>"simple",
     :item_type=>nil,
     :settings_on_pos=>{:hide=>nil}}
  end

  def create_item_response
    {:id=>"21",
     :category=>{:id=>"5047", :name=>"Cuentas por pagar - proveedores"},
     :has_no_iva_days=>false,
     :name=>"leather",
     :description=>"Brown leather wallet",
     :reference=>"CAR-195",
     :status=>"active",
     :calculation_scale=>2,
     :price=>[{:id_price_list=>1, :name=>"General", :type=>"amount", :price=>4050, :currency=>{:code=>"COP", :symbol=>"$"}}],
     :inventory=>
       {:initial_quantity=>160,
        :initial_quantity_date=>"2024-06-18",
        :unit=>"piece",
        :unit_cost=>2560,
        :available_quantity=>160,
        :negative_sale=>true,
        :warehouses=>[{:name=>"Principal", :observations=>nil, :is_default=>true, :status=>"active", :id=>"1", :cost_center=>nil, :address=>nil, :initial_quantity=>160, :available_quantity=>160, :min_quantity=>nil, :max_quantity=>nil}]},
     :accounting=>
       {:inventory=>
          {:id=>"5043",
           :id_parent=>"5038",
           :name=>"Inventario",
           :text=>"Inventario",
           :code=>nil,
           :description=>nil,
           :type=>"asset",
           :read_only=>false,
           :nature=>"debit",
           :blocked=>"no",
           :status=>"active",
           :category_rule=>{:id=>"7", :name=>"Inventario", :key=>"INVENTORY"},
           :use=>"movement",
           :show_third_party_balance=>true},
        :inventariable_purchase=>
          {:id=>"5076",
           :id_parent=>"5074",
           :name=>"Compras inventariables",
           :text=>"Compras inventariables",
           :code=>nil,
           :description=>nil,
           :type=>"expense",
           :read_only=>true,
           :nature=>"debit",
           :blocked=>"no",
           :status=>"active",
           :category_rule=>{:id=>"33", :name=>"Compras inventariables", :key=>"INVENTARIABLE_PURCHASES"},
           :use=>"movement",
           :show_third_party_balance=>true}},
     :tax=>
       [{:id=>"3",
         :name=>"IVA",
         :percentage=>"19.00",
         :description=>"",
         :status=>"active",
         :type=>"IVA",
         :category_favorable=>
           {:id=>"5035",
            :id_parent=>"5034",
            :name=>"IVA a favor",
            :text=>"IVA a favor",
            :code=>nil,
            :description=>nil,
            :type=>"asset",
            :read_only=>false,
            :nature=>"debit",
            :blocked=>"no",
            :status=>"active",
            :category_rule=>{:id=>"44", :name=>"IVA a favor", :key=>"IVA_IN_FAVOR_COL"},
            :use=>"movement",
            :show_third_party_balance=>true},
         :category_to_be_paid=>
           {:id=>"5056",
            :id_parent=>"5055",
            :name=>"Iva por pagar",
            :text=>"Iva por pagar",
            :code=>nil,
            :description=>nil,
            :type=>"liability",
            :read_only=>false,
            :nature=>"credit",
            :blocked=>"no",
            :status=>"active",
            :category_rule=>{:id=>"47", :name=>"IVA por pagar", :key=>"IVA_TO_PAY_COL"},
            :use=>"movement",
            :show_third_party_balance=>true}}],
     :custom_fields=>[],
     :product_key=>nil,
     :type=>"product",
     :item_type=>nil,
     :settings_on_pos=>{:hide=>nil}}
  end
end