module PruebasResponses
  def list_all_users_response
    [{ id: '1',
       username: nil,
       name: nil,
       last_name: nil,
       email: 'info@quincena.me',
       phone: nil,
       role: 'admin',
       status: 'active',
       language: 'es_CO',
       position: nil,
       permissions: { bank_accounts: { add: 'allow', transfer: 'allow', delete: 'allow', edit: 'allow', index: 'allow', view: 'allow', connect: 'allow' },
                      bills: { add: 'allow', delete: 'allow', edit: 'allow', index: 'allow', view: 'allow' },
                      categories: { add: 'allow', delete: 'allow', edit: 'allow', index: 'allow',
                                    view: 'allow' },
                      contacts: { add: 'allow', delete: 'allow', edit: 'allow', index: 'allow', view: 'allow',
                                  view_clients: 'allow', view_providers: 'allow', view_client: 'allow', view_provider: 'allow' },
                      company: { edit: 'allow', edit_invoice_info: 'allow', retrieve_info: 'allow',
                                 edit_invoice_template: 'allow', user_view_costs: 'allow' },
                      credit_notes: { add: 'allow', delete: 'allow', edit: 'allow', index: 'allow',
                                      view: 'allow' },
                      invoices: { add: 'allow', edit: 'allow', email: 'allow', index: 'allow', view: 'allow', void: 'allow',
                                  edit_items_prices: 'allow', edit_discount: 'allow', max_discount_allow: 100, edit_open: 'allow', edit_draft: 'allow' },
                      items: { add: 'allow', delete: 'allow', edit: 'allow', index: 'allow', view: 'allow', import: 'allow',
                               bulk_edit: 'allow' },
                      payment: { index: 'allow' },
                      recurring_invoice: { add: 'allow', delete: 'allow', edit: 'allow', index: 'allow',
                                           view: 'allow' },
                      recurring_payments: { add: 'allow', delete: 'allow', edit: 'allow', index: 'allow',
                                            view: 'allow' },
                      reports: { inventory: 'allow',
                                 cash_flow: 'allow',
                                 profit_and_loss: 'allow',
                                 retrieve_cash_in_tree: 'allow',
                                 retrieve_cash_out_tree: 'allow',
                                 retrieve_expense_tree: 'allow',
                                 retrieve_income_tree: 'allow',
                                 retrieve_item_inventory: 'allow',
                                 retrieve_sales_by_client: 'allow',
                                 retrieve_sales_by_item: 'allow',
                                 retrieve_trial_balance: 'allow',
                                 sales_by_client: 'allow',
                                 sales_by_item: 'allow',
                                 general_balance: 'allow',
                                 view_dashboard_info: 'allow',
                                 sales: 'allow',
                                 items_profit: 'allow',
                                 sales_by_seller: 'allow',
                                 taxes_and_retentions: 'allow',
                                 income_and_expense: 'allow',
                                 invoices_open: 'allow',
                                 bills_open: 'allow',
                                 transactions: 'allow',
                                 client_statement: 'allow',
                                 ledger_journal_categories: 'allow',
                                 ledger_journals: 'allow',
                                 general_ledger: 'allow',
                                 subsidiary_ledger_by_client: 'allow',
                                 exogenous: 'allow',
                                 purchases: 'allow' },
                      retentions: { add: 'allow', delete: 'allow', edit: 'allow', index: 'allow', view: 'allow',
                                    toggle_status: 'allow' },
                      taxes: { add: 'allow', delete: 'allow', edit: 'allow', index: 'allow', view: 'allow',
                               toggle_status: 'allow' },
                      terms: { add: 'allow', delete: 'allow', edit: 'allow', index: 'allow', view: 'allow' },
                      payments: { add: 'allow',
                                  delete: 'allow',
                                  edit: 'allow',
                                  view: 'allow',
                                  edit_in: 'allow',
                                  edit_out: 'allow',
                                  in: 'allow',
                                  out: 'allow',
                                  retrieve_in: 'allow',
                                  viewin: 'allow',
                                  viewout: 'allow',
                                  void: 'allow',
                                  open: 'allow',
                                  retrieve_out: 'allow' },
                      inventory_adjustments: { add: 'allow', edit: 'allow', delete: 'allow', index: 'allow',
                                               view: 'allow' },
                      debit_notes: { add: 'allow', edit: 'allow', delete: 'allow', index: 'allow',
                                     view: 'allow' },
                      journals: { add: 'allow', edit: 'allow', delete: 'allow', index: 'allow', view: 'allow' },
                      exportable: { accounting_report: 'allow',
                                    clients: 'allow',
                                    daily_sales: 'allow',
                                    transactions: 'allow',
                                    invoices: 'allow',
                                    credit_notes: 'allow',
                                    estimates: 'allow',
                                    bills: 'allow',
                                    items: 'allow',
                                    inventory: 'allow',
                                    sales: 'allow',
                                    sales_by_item: 'allow',
                                    sales_by_client: 'allow',
                                    invoices_open: 'allow',
                                    bills_open: 'allow',
                                    general_balance: 'allow',
                                    taxes_and_retentions: 'allow',
                                    profit_and_loss: 'allow',
                                    income_and_expense: 'allow',
                                    cash_flow: 'allow',
                                    sales_by_seller: 'allow',
                                    items_profit: 'allow',
                                    purchase_order: 'allow',
                                    sales_detail: 'allow',
                                    ledger_journal_categories: 'allow',
                                    ledger_journals: 'allow',
                                    general_ledger: 'allow',
                                    subsidiary_ledger_by_client: 'allow',
                                    income_debit_notes: 'allow',
                                    purchases: 'allow',
                                    report_606: 'allow',
                                    report_607: 'allow',
                                    report_608: 'allow',
                                    it1: 'allow',
                                    detailed_tax_report: 'allow',
                                    inventory_adjustment: 'allow' },
                      price_lists: { add: 'allow', edit: 'allow', view: 'allow', delete: 'allow',
                                     index: 'allow' },
                      attachments: { delete: 'allow' },
                      remissions: { add: 'allow', edit: 'allow', delete: 'allow', export: 'allow', edit_items_prices: 'allow',
                                    edit_discount: 'allow', index: 'allow', view: 'allow', void: 'allow', max_discount_allow: 100 },
                      purchase_orders: { add: 'allow', edit: 'allow', delete: 'allow', index: 'allow', view: 'allow',
                                         void: 'allow' },
                      estimates: { add: 'allow', delete: 'allow', view: 'allow', edit: 'allow', edit_items_prices: 'allow',
                                   edit_discount: 'allow', index: 'allow', max_discount_allow: 100 },
                      warehouses: { add: 'allow',
                                    edit: 'allow',
                                    delete: 'allow',
                                    view_transfer: 'allow',
                                    add_transfer: 'allow',
                                    edit_transfer: 'allow',
                                    delete_transfer: 'allow',
                                    index_transfer: 'allow',
                                    index: 'allow',
                                    view: 'allow',
                                    toggle_status: 'allow' },
                      sellers: { toggle_status: 'allow', add: 'allow', edit: 'allow', delete: 'allow', index: 'allow',
                                 view: 'allow' },
                      number_templates: { index: 'allow', view: 'allow', delete: 'allow', add: 'allow', edit: 'allow',
                                          toggle_status: 'allow' },
                      currencies: { index: 'allow', add: 'allow', edit: 'allow', delete: 'allow', view: 'allow',
                                    toggle_status: 'allow' },
                      pos_cashier: { close: 'allow', index: 'allow', open: 'allow', view: 'allow' },
                      pos_station: { add: 'allow', edit: 'allow', view: 'allow', index: 'allow',
                                     delete: 'allow' },
                      cost_centers: { add: 'allow', index: 'allow', edit: 'allow', view: 'allow', delete: 'allow',
                                      toggle_status: 'allow' },
                      variant_attributes: { add: 'allow', edit: 'allow', delete: 'allow', toggle_status: 'allow',
                                            index: 'allow', view: 'allow' },
                      custom_fields: { add: 'allow', edit: 'allow', delete: 'allow', toggle_status: 'allow', index: 'allow',
                                       view: 'allow' },
                      income_debit_notes: { add: 'allow', edit: 'allow', delete: 'allow', view: 'allow', void: 'allow',
                                            index: 'allow' },
                      closing_periods: { add: 'allow' },
                      payroll: { index: 'allow' },
                      minor_expenses: { index: 'allow', view: 'allow', add: 'allow', edit: 'allow', delete: 'allow',
                                        void: 'allow' },
                      payroll_electronic: { index: 'allow' } } }]
  end
end

